{
 "title": "ML observability",
 "time": { "from": "2025-02-18T14:29:30.186Z", "to": "2025-02-18T14:53:45.986Z" },
 "panels": [
  {
   "title": "Latency (p90)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum by (le, service_name, exported_job) (rate(default_http_server_duration_milliseconds_bucket{exported_job=~\"poc-.+\"}[1m])))",
     "legendFormat": "{{exported_job}}"
    }
   ]
  },
  {
   "title": "Request per minute (RPM)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum(rate(default_http_server_duration_milliseconds_count{exported_job=~\"poc-.+\"}[1m])) by (exported_job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(container_memory_usage_bytes{name=~\"poc-.+\"}) by (name) / sum(container_spec_memory_limit_bytes{name=~\"poc-.+\"}) by (name)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\"poc-.+\"}[5m])) by (name)  / sum((container_spec_cpu_quota{name=~\"poc-.+\"} / 100000)) by (name) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}