global:
  scrape_interval:     15s
  evaluation_interval: 15s



scrape_configs:
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']
    
  - job_name: 'otel-collector'
    scrape_interval: 5s
    static_configs:
      - targets: ['otelcol:8889']
      - targets: ['otelcol:8888']
